version: '3.0'
services:

  mysql:
    image: brightspot/mysql:mysql5.6
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

  solr:
    image: brightspot/solr:8
    ports:
      - '8080:8080'
    volumes:
      - solr-data:/var/solr/data/collection1/data

  tomcat:
    image: brightspot/tomcat:9.0-jdk11
    ports:
      - '5005:5005'
    volumes:
      - storage:/servers/tomcat/storage
      - .:${PROJECT_DIRECTORY}:cached
    environment:
      - BRIGHTSPOT_PROJECT_DIRECTORY=/code
      - CONTEXT_PROPERTIES=${PROJECT_DIRECTORY}/docker-context.properties
      - MYSQL_DATABASE=brightspot
      - ROOT_WAR=${PROJECT_DIRECTORY}/web/build/libs/web.war
      - SOLR_URL=http://solr:8080/solr/collection1

  apache:
    image: brightspot/apache:2-dims3
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - storage:/var/www/localhost/htdocs/storage

  frontend:
    image: node:24.8.0-alpine
    working_dir: /app
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app:cached
    command: sh -c "yarn install && yarn dev"
    environment:
      - VITE_HOST=0.0.0.0
    depends_on:
      - tomcat

volumes:
  mysql-data:
  solr-data:
  storage:
